sudo: required
services:
  - docker

before_install:
  - docker build  -t jayasekaraireshagmailcom/docker-react -f Dockerfile.dev .
script:
  - docker run jayasekaraireshagmailcom/docker-react npm run
